# Generated by Django 4.1.7 on 2023-03-21 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('programs', '0002_alter_program_contact_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('start_day', models.CharField(max_length=255)),
                ('end_day', models.CharField(max_length=255)),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.program')),
            ],
        ),
    ]
