# Generated by Django 4.1.7 on 2023-03-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('programs', '0001_initial'),
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('start_day', models.CharField(max_length=255)),
                ('end_day', models.CharField(max_length=255)),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lecturers.lecturer')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.program')),
            ],
        ),
    ]
