# Generated by Django 4.1.7 on 2023-03-21 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('student_payment_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purpose', models.CharField(max_length=450)),
                ('paid_via', models.CharField(max_length=255)),
                ('reference_no', models.CharField(max_length=255)),
                ('paid_on', models.DateField()),
                ('paid_by', models.CharField(max_length=450)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
