# Generated by Django 4.1.7 on 2023-03-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('id_no', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('course_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_1', to='courses.course')),
                ('course_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_2', to='courses.course')),
                ('course_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_3', to='courses.course')),
                ('course_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_4', to='courses.course')),
                ('course_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_5', to='courses.course')),
            ],
        ),
    ]
